### ISSUE TITLE
custom_command example

### ISSUE THREAD

**Issue by foxsam21** [jackoson/squeezebox-controller#3]
Can we get an example of custom_command I couldn't figure it out so easily. thanks

**Comment by samtherussell** [comment]
Sorry, yeah. I'll try and explain it better. I've also updated the [docs ](https://squeezebox-controller.readthedocs.io/en/latest/?badge=latest#squeezebox_controller.SqueezeBoxController.add_custom_command) slightly. The function will receive a dictionary as its first argument which contains helper functions. Optionally, it can also accept a second argument, which will be whatever you pass to `custom_command` as the second argument when you call it. 

Here's an example of one I use.

```python
from squeezebox_controller import commands

def morning(helper, details):
      if "player" not in details:
        raise Exception("Player not specified")
      mac_addresses = helper['player_lookup']
      player_mac = mac_addresses[details['player']]
      # turn on squeeebox
      helper['make_request'](player_mac, commands["POWER ON"])
      # make custom request that plays my favourite radio show
      action_url = helper['base_url'] + "/plugins/Favorites/index.html?action=play&index=1&player="
      helper['requests'].get(action_url+player_mac)

x.add_custom_command("morning_radio", morning, True)
x.custom_command("morning_radio", {"player": "kitchen"})
x.simple_command({"command": "VOLUME UP"})
```

Note, because I set the caching flag to True on ``add_custom_command``, the player was remembered for the subsequent VOLUME UP command.

**Comment by foxsam21** [comment]
I was looking to just add a simple command. I wanted a command to pause and another to unpause not the standard pause which toggles. in the end I cheated a bit and added to the commands dict  because it was easier for me.
```
from squeezebox_controller import SqueezeBoxController as SBC, commands

commands.update({"PAUSE on": ["pause", "1"],"PAUSE off": ["pause", "0"]})

x=SBC('LMServer',9000)

params = {
    "player": 'piCorePlayer',
    "command": 'PAUSE on'
}
x.simple_command(params)
```

**Comment by foxsam21** [comment]
Also if I can ask why do you need a custom command for playing favorites? can't it all be done using simple commands in its own function? (asking bec I'm curious for the need)
I added favorites by: `commands.update({"FAV1":["favorites","playlist","play","item_id:0"]})
` so it can use the jsonrpc interface.
```
def morning(player)
    player 'power on'
    player 'play fav #1'
    player 'vol up'
```

**Comment by samtherussell** [comment]
yes, that works too!
